### ISSUE TITLE
Ubuntu 16.04 LTS x64 compability

### ISSUE THREAD

**Issue by ep4devops** [nopernik/sshpry#3]
In Ubuntu 16.04 LTS x64 is has to be

`out = re.findall('read\(11, `

instead of 

`out = re.findall('read\(10, `

**Comment by nopernik** [comment]
Actually it is not Ubuntu release problem, the number after read(XX) is a file descriptor of standard output of specific TTY. Every TTY might have different numbers. There is a workaround in version 2: https://github.com/nopernik/SSHPry2.0
